/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsTermsPolicyRouteImport } from './routes/settings/terms-policy'
import { Route as SettingsSalaryInfoRouteImport } from './routes/settings/salary-info'
import { Route as SettingsEditScheduleRouteImport } from './routes/settings/edit-schedule'
import { Route as SettingsEditSalaryRouteImport } from './routes/settings/edit-salary'
import { Route as OnboardingScheduleRouteImport } from './routes/onboarding/schedule'
import { Route as OnboardingSalaryRouteImport } from './routes/onboarding/salary'
import { Route as OnboardingCompletionRouteImport } from './routes/onboarding/completion'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTermsPolicyRoute = SettingsTermsPolicyRouteImport.update({
  id: '/settings/terms-policy',
  path: '/settings/terms-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSalaryInfoRoute = SettingsSalaryInfoRouteImport.update({
  id: '/settings/salary-info',
  path: '/settings/salary-info',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEditScheduleRoute = SettingsEditScheduleRouteImport.update({
  id: '/settings/edit-schedule',
  path: '/settings/edit-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEditSalaryRoute = SettingsEditSalaryRouteImport.update({
  id: '/settings/edit-salary',
  path: '/settings/edit-salary',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingScheduleRoute = OnboardingScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingSalaryRoute = OnboardingSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCompletionRoute = OnboardingCompletionRouteImport.update({
  id: '/completion',
  path: '/completion',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding/completion': typeof OnboardingCompletionRoute
  '/onboarding/salary': typeof OnboardingSalaryRoute
  '/onboarding/schedule': typeof OnboardingScheduleRoute
  '/settings/edit-salary': typeof SettingsEditSalaryRoute
  '/settings/edit-schedule': typeof SettingsEditScheduleRoute
  '/settings/salary-info': typeof SettingsSalaryInfoRoute
  '/settings/terms-policy': typeof SettingsTermsPolicyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding/completion': typeof OnboardingCompletionRoute
  '/onboarding/salary': typeof OnboardingSalaryRoute
  '/onboarding/schedule': typeof OnboardingScheduleRoute
  '/settings/edit-salary': typeof SettingsEditSalaryRoute
  '/settings/edit-schedule': typeof SettingsEditScheduleRoute
  '/settings/salary-info': typeof SettingsSalaryInfoRoute
  '/settings/terms-policy': typeof SettingsTermsPolicyRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding/completion': typeof OnboardingCompletionRoute
  '/onboarding/salary': typeof OnboardingSalaryRoute
  '/onboarding/schedule': typeof OnboardingScheduleRoute
  '/settings/edit-salary': typeof SettingsEditSalaryRoute
  '/settings/edit-schedule': typeof SettingsEditScheduleRoute
  '/settings/salary-info': typeof SettingsSalaryInfoRoute
  '/settings/terms-policy': typeof SettingsTermsPolicyRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/home'
    | '/login'
    | '/onboarding/completion'
    | '/onboarding/salary'
    | '/onboarding/schedule'
    | '/settings/edit-salary'
    | '/settings/edit-schedule'
    | '/settings/salary-info'
    | '/settings/terms-policy'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/home'
    | '/login'
    | '/onboarding/completion'
    | '/onboarding/salary'
    | '/onboarding/schedule'
    | '/settings/edit-salary'
    | '/settings/edit-schedule'
    | '/settings/salary-info'
    | '/settings/terms-policy'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/home'
    | '/login'
    | '/onboarding/completion'
    | '/onboarding/salary'
    | '/onboarding/schedule'
    | '/settings/edit-salary'
    | '/settings/edit-schedule'
    | '/settings/salary-info'
    | '/settings/terms-policy'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SettingsEditSalaryRoute: typeof SettingsEditSalaryRoute
  SettingsEditScheduleRoute: typeof SettingsEditScheduleRoute
  SettingsSalaryInfoRoute: typeof SettingsSalaryInfoRoute
  SettingsTermsPolicyRoute: typeof SettingsTermsPolicyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terms-policy': {
      id: '/settings/terms-policy'
      path: '/settings/terms-policy'
      fullPath: '/settings/terms-policy'
      preLoaderRoute: typeof SettingsTermsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/salary-info': {
      id: '/settings/salary-info'
      path: '/settings/salary-info'
      fullPath: '/settings/salary-info'
      preLoaderRoute: typeof SettingsSalaryInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/edit-schedule': {
      id: '/settings/edit-schedule'
      path: '/settings/edit-schedule'
      fullPath: '/settings/edit-schedule'
      preLoaderRoute: typeof SettingsEditScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/edit-salary': {
      id: '/settings/edit-salary'
      path: '/settings/edit-salary'
      fullPath: '/settings/edit-salary'
      preLoaderRoute: typeof SettingsEditSalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/schedule': {
      id: '/onboarding/schedule'
      path: '/schedule'
      fullPath: '/onboarding/schedule'
      preLoaderRoute: typeof OnboardingScheduleRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/salary': {
      id: '/onboarding/salary'
      path: '/salary'
      fullPath: '/onboarding/salary'
      preLoaderRoute: typeof OnboardingSalaryRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/completion': {
      id: '/onboarding/completion'
      path: '/completion'
      fullPath: '/onboarding/completion'
      preLoaderRoute: typeof OnboardingCompletionRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
  }
}

interface OnboardingRouteRouteChildren {
  OnboardingCompletionRoute: typeof OnboardingCompletionRoute
  OnboardingSalaryRoute: typeof OnboardingSalaryRoute
  OnboardingScheduleRoute: typeof OnboardingScheduleRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingCompletionRoute: OnboardingCompletionRoute,
  OnboardingSalaryRoute: OnboardingSalaryRoute,
  OnboardingScheduleRoute: OnboardingScheduleRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SettingsEditSalaryRoute: SettingsEditSalaryRoute,
  SettingsEditScheduleRoute: SettingsEditScheduleRoute,
  SettingsSalaryInfoRoute: SettingsSalaryInfoRoute,
  SettingsTermsPolicyRoute: SettingsTermsPolicyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
