use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{menubar, notifications, preferences, recovery, user_settings};
    use crate::tray;

    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Menubar panel
        menubar::init_menubar,
        menubar::show_menubar_panel,
        // Preferences
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        // Notifications
        notifications::send_native_notification,
        // Recovery
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        // User settings
        user_settings::load_user_settings,
        user_settings::save_user_settings,
        user_settings::is_onboarding_completed,
        user_settings::reset_all_data,
        // Tray icon
        tray::set_tray_icon_state,
        tray::set_tray_title,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/tauri-bindings.gen.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/tauri-bindings.gen.ts");
    }
}
